In [2]:
!pip install anndata scanpy

import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

Collecting anndata
  Downloading anndata-0.12.10-py3-none-any.whl.metadata (9.9 kB)
Collecting scanpy
  Downloading scanpy-1.12.1-py3-none-any.whl.metadata (8.4 kB)
Collecting array-api-compat>=1.7.1 (from anndata)
  Downloading array_api_compat-1.14.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata) (3.16.0)
Collecting legacy-api-wrap (from anndata)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata) (8.4.0)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.0.2)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata) (26.0)
Requirement already satisfied: pandas!=2.1.2,<3,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.2.2)
Requirement already satisfied: scipy!=1.17.0,>=1.12 in /usr/local/lib/python3.12/dist-packages (from anndata) (1.16.3)
Collecting zarr!=3.0.*,>=2.18.7 (from anndata)
  Downloading zarr-3.1.6-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from scanpy) (2026.2.25)
Collecting fast-array-utils>=1.4 (from fast-array-utils[accel,sparse]>=1.4->scanpy)
  Downloading fast_array_utils-1.4.1-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.5.3)
Requirement already satisfied: matplotlib>=3.9 in /usr/local/lib/python3.12/dist-packages (from scanpy) (3.10.0)
Requirement already satisfied: networkx>=2.8.8 in /usr/local/lib/python3.12/dist-packages (from scanpy) (3.6.1)
Requirement already satisfied: numba>=0.60 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.60.0)
Collecting pandas!=2.1.2,<3,>=2.1.0 (from anndata)
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 5.8 MB/s eta 0:00:00
Requirement already satisfied: patsy in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.0.2)
Requirement already satisfied: pynndescent>=0.5.13 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.6.0)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.6.1)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.13.2)
Collecting session-info2 (from scanpy)
  Downloading session_info2-0.4.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from scanpy) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from scanpy) (4.15.0)
Requirement already satisfied: umap-learn>=0.5.12 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.5.12)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.60->scanpy) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6->scanpy) (3.6.0)
Collecting donfig>=0.8 (from zarr!=3.0.*,>=2.18.7->anndata)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata) (1.8.0)
Collecting numcodecs>=0.14 (from zarr!=3.0.*,>=2.18.7->anndata)
  Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.9->scanpy) (1.17.0)
Downloading anndata-0.12.10-py3-none-any.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.6/176.6 kB 10.6 MB/s eta 0:00:00
Downloading scanpy-1.12.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 66.6 MB/s eta 0:00:00
Downloading array_api_compat-1.14.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 3.8 MB/s eta 0:00:00
Downloading fast_array_utils-1.4.1-py3-none-any.whl (39 kB)
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 106.9 MB/s eta 0:00:00
Downloading zarr-3.1.6-py3-none-any.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 20.4 MB/s eta 0:00:00
Downloading session_info2-0.4.1-py3-none-any.whl (17 kB)
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 96.4 MB/s eta 0:00:00
Installing collected packages: session-info2, numcodecs, legacy-api-wrap, fast-array-utils, donfig, array-api-compat, zarr, pandas, anndata, scanpy
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
Successfully installed anndata-0.12.10 array-api-compat-1.14.0 donfig-0.8.1.post1 fast-array-utils-1.4.1 legacy-api-wrap-1.5 numcodecs-0.16.5 pandas-2.3.3 scanpy-1.12.1 session-info2-0.4.1 zarr-3.1.6

0.12.10

/tmp/ipykernel_6631/38904509.py:7: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(ad.__version__)

In [1]:
import numpy as np
import pandas as pd
import anndata as ad
import scanpy as sc
from scipy.sparse import csr_matrix

print(f"anndata version: {ad.__version__}")
print(f"scanpy version: {sc.__version__}")
print("All imports successful!")

anndata version: 0.12.10
scanpy version: 1.12.1
All imports successful!

/tmp/ipykernel_7085/2182884543.py:7: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(f"anndata version: {ad.__version__}")
/tmp/ipykernel_7085/2182884543.py:8: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print(f"scanpy version: {sc.__version__}")

In [2]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
adata

AnnData object with n_obs × n_vars = 100 × 2000

In [5]:
print("AnnData object with n_obs x n_vars = 100 x 2000")

AnnData object with n_obs x n_vars = 100 x 2000

In [6]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 126442 stored elements and shape (100, 2000)>

In [8]:
import scanpy as sc
import numpy as np

# Create a sparse matrix (example)
from scipy.sparse import csr_matrix
matrix = csr_matrix(np.random.rand(100, 2000))
print(matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 200000 stored elements and shape (100, 2000)>
  Coords	Values
  (0, 0)	0.2803881667569521
  (0, 1)	0.5008023525155261
  (0, 2)	0.590492833841825
  (0, 3)	0.6179080841233668
  (0, 4)	0.8417661756493678
  (0, 5)	0.6132265241807046
  (0, 6)	0.23046955177300676
  (0, 7)	0.531960900634174
  (0, 8)	0.06491929877614677
  (0, 9)	0.3935899030279314
  (0, 10)	0.9125532533694134
  (0, 11)	0.8290891264669491
  (0, 12)	0.958071031447093
  (0, 13)	0.11865768219252748
  (0, 14)	0.7489995462744212
  (0, 15)	0.5619945027331277
  (0, 16)	0.10039857085291448
  (0, 17)	0.3305141309401378
  (0, 18)	0.030668093721282652
  (0, 19)	0.8360545387360606
  (0, 20)	0.7776330891321166
  (0, 21)	0.9332671069513817
  (0, 22)	0.05922104662950978
  (0, 23)	0.3262038968566374
  (0, 24)	0.06261784153736238
  :	:
  (99, 1975)	0.2703469620695471
  (99, 1976)	0.8441342932582685
  (99, 1977)	0.3855081374665441
  (99, 1978)	0.35560973591357337
  (99, 1979)	0.4296051547347203
  (99, 1980)	0.6658058078047205
  (99, 1981)	0.5655570586375176
  (99, 1982)	0.01452907241855561
  (99, 1983)	0.06224288243318232
  (99, 1984)	0.290970116302691
  (99, 1985)	0.8759178379697424
  (99, 1986)	0.5256052955129058
  (99, 1987)	0.680675543547497
  (99, 1988)	0.11693409293740853
  (99, 1989)	0.855931981793469
  (99, 1990)	0.22679541668499958
  (99, 1991)	0.07769844566147155
  (99, 1992)	0.13342169878030996
  (99, 1993)	0.31977561626939544
  (99, 1994)	0.5832431367142489
  (99, 1995)	0.9297156271497719
  (99, 1996)	0.049803130126837125
  (99, 1997)	0.030115161209620545
  (99, 1998)	0.02197476998975778
  (99, 1999)	0.6589713823832499

In [9]:
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:10])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')

In [11]:
import scanpy as sc
import pandas as pd

# Load your data
adata = sc.datasets.pbmc68k_reduced()

# This will show the index (the output you pasted)
print(adata.obs.index[:10])

Index(['AAAGCCTGGCTAAC-1', 'AAATTCGATGCACA-1', 'AACACGTGGTCTTT-1',
       'AAGTGCACGTGCTA-1', 'ACACGAACGGAGTG-1', 'ACAGTTCTTAGCCA-1',
       'ACATTCTGACTACG-1', 'ACCCTCGAGTGAGG-1', 'ACTGGCCTTTTCGT-1',
       'ACTTGGGAACCAGT-1'],
      dtype='object', name='index')

In [18]:
# Use actual cell names and actual gene names
adata[["AAAGCCTGGCTAAC-1", "AAGTGCACGTGCTA-1"], ["HES4", "TNFRSF4"]]

View of AnnData object with n_obs × n_vars = 2 × 2
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [21]:
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
adata.obs

,bulk_labels,n_genes,percent_mito,n_counts,S_score,G2M_score,phase,louvain,cell_type
index,,,,,,,,,
AAAGCCTGGCTAAC-1,CD14+ Monocyte,1003,0.023856,2557.0,-0.119160,-0.816889,G1,1,B
AAATTCGATGCACA-1,Dendritic,1080,0.027458,2695.0,0.067026,-0.889498,S,1,T
AACACGTGGTCTTT-1,CD56+ NK,1228,0.016819,3389.0,-0.147977,-0.941749,G1,3,Monocyte
AAGTGCACGTGCTA-1,CD4+/CD25 T Reg,1007,0.011797,2204.0,0.065216,1.469291,G2M,9,T
ACACGAACGGAGTG-1,Dendritic,1178,0.017277,3878.0,-0.122974,-0.868185,G1,2,Monocyte
...,...,...,...,...,...,...,...,...,...
TGGCACCTCCAACA-8,Dendritic,1166,0.008840,3733.0,-0.124456,-0.867484,G1,2,T
TGTGAGTGCTTTAC-8,Dendritic,1014,0.022068,2311.0,-0.298056,-0.649070,G1,1,B
TGTTACTGGCGATT-8,CD4+/CD25 T Reg,1079,0.012821,3354.0,0.216895,-0.527338,S,0,Monocyte
TTCAGTACCGGGAA-8,CD19+ B,1030,0.014169,2823.0,0.139054,-0.981590,S,4,T
TTGAGGTGGAGAGC-8,Dendritic,1552,0.010886,4685.0,-0.148449,-0.674752,G1,2,B

In [22]:
adata

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain', 'cell_type'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [24]:
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))
adata.obsm

AxisArrays with keys: X_pca, X_umap

In [25]:
adata

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain', 'cell_type'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs', 'gene_stuff'
    obsp: 'connectivities', 'distances'

In [26]:
adata.uns["random"] = [1, 2, 3]
adata.uns

{'bulk_labels_colors': array(['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b',
        '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], dtype=object),
 'louvain': {'params': {'random_state': array([0]), 'resolution': array([1])}},
 'louvain_colors': array(['#023fa5', '#7d87b9', '#bec1d4', '#d6bcc0', '#bb7784', '#8e063b',
        '#4a6fe3', '#8595e1', '#b5bbe3', '#e6afb9', '#e07b91'],
       dtype=object),
 'neighbors': {'params': {'method': 'umap', 'n_neighbors': array([10])}},
 'pca': {'variance': array([30.928047 , 21.182432 , 14.686322 , 11.570731 ,  9.232856 ,
          7.3497834,  4.338316 ,  3.197439 ,  3.1584399,  2.910167 ,
          2.649945 ,  2.540031 ,  2.4057367,  2.3872852,  2.2644212,
          2.2250588,  2.189688 ,  2.134691 ,  2.0775423,  2.0560663,
          2.007874 ,  1.9969993,  1.9606696,  1.9441428,  1.9129871,
          1.9063067,  1.8529838,  1.8260264,  1.7946786,  1.7489465,
          1.7449841,  1.7298484,  1.70099  ,  1.6571085,  1.6406441,
          1.6235017,  1.6012688,  1.5806534,  1.5531204,  1.5331998,
          1.5166894,  1.4852371,  1.4748584,  1.4530103,  1.4340347,
          1.4083625,  1.375356 ,  1.3701098,  1.356156 ,  1.3449155],
        dtype=float32),
  'variance_ratio': array([0.09770954, 0.06692067, 0.04639781, 0.03655487, 0.02916893,
         0.02321983, 0.01370584, 0.01010152, 0.00997831, 0.00919395,
         0.00837185, 0.0080246 , 0.00760033, 0.00754204, 0.00715388,
         0.00702952, 0.00691778, 0.00674403, 0.00656348, 0.00649563,
         0.00634338, 0.00630903, 0.00619425, 0.00614204, 0.00604361,
         0.00602251, 0.00585405, 0.00576888, 0.00566984, 0.00552537,
         0.00551285, 0.00546503, 0.00537386, 0.00523523, 0.00518321,
         0.00512905, 0.00505881, 0.00499368, 0.0049067 , 0.00484377,
         0.00479161, 0.00469224, 0.00465945, 0.00459043, 0.00453048,
         0.00444937, 0.0043451 , 0.00432852, 0.00428444, 0.00424893],
        dtype=float32)},
 'rank_genes_groups': {'names': array([('RGS19', 'ITM2A', 'CAPG', 'CCL5', 'CD8B', 'C1QA', 'CD79A', 'PRSS57', 'GNLY', 'CST3'),
         ('HIST1H4C', 'RPL39', 'GABARAPL2', 'GNLY', 'CD8A', 'PSAP', 'CD79B', 'SNHG7', 'NKG7', 'LYZ'),
         ('IL32', 'TIMM10', 'FDX1', 'NKG7', 'RP11-291B21.2', 'COX14', 'MS4A1', 'SERPINB1', 'CD7', 'LST1'),
         ('GSTK1', 'CWC15', 'CRIP1', 'GZMH', 'CD7', 'NEAT1', 'IGJ', 'C19orf77', 'CLIC3', 'IRF7'),
         ('SKP1', 'CXCR4', 'GATA3', 'CHCHD7', 'NECAP2', 'NUP214', 'IGLL5', 'SPINK2', 'SPON2', 'C10orf54'),
         ('TMBIM6', 'LSM5', 'HPCAL1', 'SRSF2', 'ANAPC16', 'RAB7A', 'SPIB', 'IMPDH2', 'TYROBP', 'ZNHIT1'),
         ('CALM3', 'LSMD1', 'DNAJC1', 'ANXA1', 'SAMD3', 'OAS1', 'UBE2J1', 'H2AFY', 'GZMB', 'CD33'),
         ('COPE', 'SUPT4H1', 'C20orf27', 'MRFAP1', 'YWHAB', 'HMGB2', 'SMARCB1', 'EGFL7', 'PLAC8', 'ILK'),
         ('CD3E', 'SRSF7', 'MIEN1', 'DUSP2', 'CARS', 'SLTM', 'MZB1', 'CYTL1', 'FCER1G', 'IL32'),
         ('CAPN2', 'MTDH', 'ACAA1', 'KLRB1', 'HMGA1', 'TMEM176B', 'CCDC50', 'SNHG8', 'CTSW', 'CPVL'),
         ('ICAM3', 'SIAH2', 'EMB', 'CST7', 'S100B', 'SRGN', 'C16orf74', 'SOX4', 'CST7', 'SRRM2'),
         ('TMBIM4-1', 'CAPN2', 'DENND2D', 'IRF1', 'NDFIP1', 'SOD2', 'CAPG', 'C6orf48', 'MIEN1', 'HLA-DPB1'),
         ('MZT2B', 'EIF3E', 'EBP', 'FYB', 'HMHA1', 'TMEM176A', 'CD74', 'HSP90AB1', 'IGFBP7', 'MNDA'),
         ('PPP2R5C', 'PLGRKT', 'PMVK', 'GZMK', 'MRPS25', 'RAB10', 'TNFRSF13B', 'NFE2', 'GZMA', 'C19orf43'),
         ('CLPP', 'IGJ', 'SPG21', 'PSMD7', 'SSU72', 'SLC11A1', 'FKBP11', 'IGFBP7', 'ITGB2', 'APEX1'),
         ('C10orf54', 'APBB1IP', 'GZMK', 'ANXA5', 'GZMM', 'IFI30', 'AL928768.3', 'ZFAS1', 'MATK', 'GPX1'),
         ('OSTF1', 'POU2AF1', 'ADD3', 'ANKRD12', 'POMP', 'SSR3', 'ZNF706', 'EBPL', 'MSN', 'IFT20'),
         ('TCEAL8', 'UCHL3', 'MRPS21', 'RCSD1', 'AMICA1', 'COMMD5', 'SUB1', 'H1FX', 'DCXR', 'SEPT9'),
         ('CD3D', 'CCT6A', 'CCT6A', 'CCDC115', 'SNHG15', 'TNFSF13B', 'PLAC8', 'HSD17B11', 'MCM7', 'ANXA1'),
         ('KLF3', 'RP11-277L2.3', 'GZMA', 'EIF3E', 'ID2', 'TYROBP', 'HLA-DRB5', 'NME4', 'MEA1', 'APH1A'),
         ('TAPBP', 'NHP2', 'CORO1B', 'HOPX', 'CCR7', 'RBP7', 'SPCS2', 'NPM3', 'LAT2', 'ESD'),
         ('WIPF1', 'FLT3LG', 'LDHA', 'GLOD4', 'OFD1', 'S100A8', 'TXNDC15', 'NGFRAP1', 'XCL1', 'AIF1'),
         ('ANXA11', 'LBH', 'COX6A1', 'HLA-DPB1', 'C16orf13', 'S1PR4', 'GNG7', 'HNRNPA1', 'NDUFA2', 'TMBIM6'),
         ('SRRM2', 'TIMM13', 'OTUB1', 'ATP6V1G1', 'CUTA', 'ZNF706', 'C19orf24', 'CAT', 'HOPX', 'FCER1A'),
         ('NUDCD2', 'ADRM1', 'CCL5', 'STUB1', 'TCEB2', 'FPR1', 'MRPS33', 'IGLL1', 'TTC38', 'CAT'),
         ('CD3G', 'MRPS6', 'EID1', 'COX7B', 'PPIG', 'PHPT1', 'HLA-DPA1', 'PNISR', 'UPP1', 'HMHA1'),
         ('RAB7A', 'RP11-489E7.4', 'CNPY2', 'BFAR', 'TMEM126B', 'ZFAS1', 'HLA-DMA', 'KIAA0125', 'IMP3', 'DYNLRB1'),
         ('CCDC107', 'H2AFJ', 'RNF138', 'CCDC107', 'TBC1D10C', 'LRRC25', 'ISG20', 'SLC39A3', 'CD300A', 'POP5'),
         ('ALOX5AP', 'DHRS7', 'ELOVL5', 'ASCC2', 'HSD17B11', 'SUMO3', 'CD40', 'CAPN1', 'GGNBP2', 'CLIC3'),
         ('PTPRC', 'HIST1H1E', 'UBE2F', 'KLRG1', 'CCDC109B', 'GABARAPL2', 'BANK1', 'HSPD1', 'CD160', 'DDX5'),
         ('ATPIF1', 'HCST', 'ATP5I', 'LPXN', 'C9orf78', 'MT-ND3', 'SSR4', 'NPM1', 'MAGOH', 'POLR2G'),
         ('SIT1', 'CD4', 'CD4', 'DNAJB1', 'HMGB2', 'PRAM1', 'CCT3', 'EPB41L4A-AS1', 'AHSA1', 'HLA-DPA1'),
         ('NUCKS1', 'SCP2', 'AHSA1', 'NSRP1', 'RGS10', 'SCAMP2', 'PTPRCAP', 'SYPL1', 'FGFBP2', 'SPINT2'),
         ('ATP6V1G1', 'GGNBP2', 'TLN1', 'OTUB1', 'ARL4C', 'C19orf53', 'PNOC', 'HMGA1', 'SRGN', 'ARL4C'),
         ('PLP2', 'SSB', 'UFD1L', 'ITGA4', 'PCNP', 'CCDC115', 'LTB', 'SDHC', 'PRF1', 'HLA-DQA1'),
         ('FYB', 'COA3', 'PPDPF', 'LAG3', 'TTC39C', 'SSR4', 'EAF2', 'MPP1', 'CD63', 'COX17'),
         ('IDH2', 'ABI1', 'IFITM3', 'EXOG', 'CD27', 'S100A9', 'HLA-DQA1', 'APEX1', 'CCL4', 'MRFAP1'),
         ('CD247', 'SQSTM1', 'CSTB', 'HSD17B11', 'HSPB1', 'BST1', 'HLA-DPB1', 'C1orf228', 'GOLGA7', 'PPA1'),
         ('LGALS3', 'EIF4A2', 'CTSC', 'PDAP1', 'WBSCR22', 'TPR', 'SMIM14', 'RP11-620J15.3', 'ID2', 'MIEN1'),
         ('ATP6V1E1', 'SH3GL1', 'COA6', 'PPDPF', 'ARID4B', 'G0S2', 'HAX1', 'TKT', 'GZMM', 'UNC119'),
         ('PSAP', 'POMP', 'GLRX', 'DHRS7', 'PHB', 'ICAM4', 'ACP5', 'EGR1', 'SDF2L1', 'LEPROTL1'),
         ('S100A4', 'PCNA', 'NAA20', 'DNAJC1', 'AP2S1', 'MRPS25', 'SDF2L1', 'CD164', 'AKR1C3', 'SF3B2'),
         ('PQBP1', 'BST2', 'PRMT2', 'FGFBP2', 'MAD2L2', 'C1QB', 'NCF1', 'DTD1', 'TXNIP', 'HLA-DMB'),
         ('PIK3IP1', 'TRIAP1', 'C10orf118', 'CCDC167', 'NDUFA2', 'NOP10', 'RNF167', 'ATP5B', 'GIMAP7', 'SERTAD3'),
         ('PSMB2', 'NDUFB10', 'NUCB2', 'HCST', 'CPA5', 'LYL1', 'AC079767.4', 'RAB13', 'CD247', 'PPIB'),
         ('PTPN7', 'ATP5J2', 'GTF3C6', 'TMEM208', 'PSMA7', 'UNC93B1', 'HIST1H4C', 'STMN1', 'FLT3LG', 'RABAC1'),
         ('NCOR1', 'SSR3', 'HCST', 'ISG20', 'NENF', 'MRPL9', 'TNFRSF17', 'CDK6', 'APMAP', 'C9orf78'),
         ('CNN2', 'PRDX2', 'NDUFA1', 'PPIB', 'HMOX2', 'SIAH2', 'ERH', 'ZFP36L2', 'PRMT2', 'SERPINB1'),
         ('HAX1', 'LDHA', 'CD2', 'SIAH2', 'JUNB', 'ATP5O', 'FGR', 'CCT8', 'ANXA11', 'LAMTOR1'),
         ('CCR10', 'ESD', 'IL7R', 'NGFRAP1', 'TRAM1', 'NFE2', 'HLA-DRB1', 'COMT', 'TIMM13', 'HLA-DQA2'),
         ('MRPL21', 'HNRNPR', 'PPM1G', 'RBX1', 'PNISR', 'AIF1', 'SNX2', 'EIF3L', 'CCT3', 'PLD4'),
         ('PBXIP1', 'PSMB6', 'GTF2E2', 'PIK3IP1', 'LSM4', 'COA1', 'MANF', 'TALDO1', 'SNORD3B-2', 'FCER1G'),
         ('CD37', 'PDLIM1', 'PGAM1', 'DDX5', 'PRKCQ-AS1', 'POLR3K', 'TXN', 'ANP32B', 'C1orf21', 'CD3D'),
         ('TPM3', 'CTSC', 'DAXX', 'SSB', 'AHSA1', 'FCN1', 'HLA-DRA', 'DDAH2', 'IFITM2', 'FOS'),
         ('ANXA5', 'PTPLAD2', 'POMP', 'UBALD2', 'POLD4', 'EID1', 'MIF', 'GPX1', 'APEX1', 'PPM1G'),
         ('BLOC1S4', 'CD3D', 'ATP5B', 'MARCKSL1', 'POLR2I', 'DYNLT1', 'S1PR4', 'SERPINB6', 'DAP3', 'RPS27L'),
         ('NOP10', 'DDX39A', 'NIFK', 'HNRNPDL', 'TCP1', 'JOSD2', 'AHSA1', 'AKR1C3', 'TCEAL8', 'SNHG8'),
         ('LCK', 'PPA1', 'ZFP36L2', 'GZMA', 'SMAP2', 'LTB', 'REEP5', 'NFKBIA', 'TALDO1', 'COX7C'),
         ('LEPROTL1', 'IL32', 'JOSD2', 'CD52', 'CTSD', 'STXBP2', 'ERLEC1', 'CREG1', 'UQCRC1', 'MZT2B'),
         ('COX14', 'SRSF2', 'CD3D', 'PARK7', 'NDUFS8', 'SDHC', 'EIF3D', 'IRF1', 'EFHD2', 'BID'),
         ('TPM4', 'BTG1', 'NDNL2', 'SUB1', 'TOP1', 'CAPG', 'APH1A', 'SPINT2', 'CCT6A', 'AMICA1'),
         ('PKM', 'MIF', 'RNASET2', 'C19orf24', 'POLR2G', 'IRF1', 'C19orf53', 'RSL1D1', 'HNRNPR', 'AP2S1'),
         ('RWDD1', 'ARF6', 'EIF2AK1', 'EMC7', 'BLOC1S4', 'ABI3', 'NDUFAB1', 'ANXA1', 'TIGIT', 'RWDD1'),
         ('SELT', 'SCAMP2', 'PARK7', 'NINJ2', 'SNRNP70', 'NDUFA2', 'HLA-DMB', 'HIST1H4C', 'STK17A', 'ZYX'),
         ('DYNLRB1', 'COX7B', 'TMEM256', 'AGTRAP', 'SEPT7', 'S100A10', 'COX14', 'LDHB', 'MZT2B', 'MFSD1'),
         ('TIGIT', 'NT5C3B', 'MRPS33', 'PSMB2', 'RPS27L', 'TXN', 'PRDX1', 'LAT2', 'HMGB2', 'BBX'),
         ('RNF167', 'NCOR1', 'PLGRKT', 'CD8B', 'RPL39', 'OSBPL8', 'CRIP1', 'NUCB2', 'OSTF1', 'CD3E'),
         ('FAM65B', 'SNRNP70', 'CCDC167', 'NEAT1', 'ATXN7L3B', 'ATP5J2', 'KIAA0125', 'ALKBH7', 'C1orf162', 'TMBIM4-1'),
         ('CAPN1', 'RBX1', 'LIMS1', 'EFHD2', 'CCNI', 'SQSTM1', 'MRPS6', 'LYL1', 'ZNHIT1', 'SERPINF1'),
         ('LAT', 'ANXA5', 'CALR', 'BRD7', 'WIBG', 'EIF4A2', 'TMEM256', 'MRPL9', 'UBE2F', 'LY86'),
         ('CWC25', 'CORO1B', 'CD40LG', 'NAP1L1', 'ATP6V0E1', 'MRPL48', 'PDLIM1', 'HNRNPDL', 'PSMD13', 'MLF2'),
         ('GOLGA7', 'TCP1', 'DPEP2', 'NDUFAF3', 'GZMK', 'FCER1G', 'HVCN1', 'IL1B', 'ABI3', 'MPP1'),
         ('ARL6IP5', 'BFAR', 'MRPL48', 'ZNRD1', 'CXCR4', 'ACAA1', 'CCDC167', 'C1orf21', 'MRPS6', 'HLA-DRA'),
         ('PRR4', 'BANK1', 'COX17', 'MLF2', 'ILF3', 'RNASET2', 'SP140', 'LSMD1', 'AOAH', 'NME4'),
         ('EIF4H', 'PRDX1', 'FLI1', 'NDUFA4', 'COX17', 'ADRM1', 'CSTB', 'MATK', 'OGG1', 'CTSS'),
         ('TXN', 'ZNF524', 'SSR4', 'U2AF1', 'VIMP', 'GSTK1', 'CD37', 'NENF', 'PSMC3', 'ANKRD12'),
         ('NINJ2', 'LIMS1', 'PPIB', 'ZFAS1', 'S100A6', 'CD4', 'CUTA', 'GSTP1', 'SDHC', 'CTSH'),
         ('NOSIP', 'DAP3', 'CD47', 'CD28', 'LYAR', 'EBP', 'MRPS21', 'HHEX', 'C9orf78', 'CFD'),
         ('DNAJC7', 'SEC62', 'SNHG8', 'LST1', 'BIN3', 'SMAP2', 'SMAP2', 'PLD4', 'ACAA2', 'TIMM10'),
         ('COMMD3', 'EGR1', 'NDUFAB1', 'TOMM7', 'ATP5J2', 'PSMB2', 'ATP5B', 'NCL', 'SEC62', 'MRPL21'),
         ('CYB561A3', 'NBEAL1', 'MTDH', 'LY9', 'FOS', 'RHOC', 'ISCU', 'CCNI', 'NDUFB2', 'HLA-DRB1'),
         ('SH3YL1', 'GOLGA7', 'LAMTOR1', 'TPM3', 'PNN', 'PSMC3', 'HLA-DQA2', 'MARCKSL1', 'SPCS2', 'TMEM256'),
         ('CD27', 'SLC25A39', 'LAMTOR4', 'NUCKS1', 'CTSS', 'SCP2', 'BCAS4', 'NDUFA8', 'LCK', 'SRM'),
         ('TRAF3IP3', 'GIMAP7', 'AES', 'PRR7', 'CCT6A', 'NAP1L1', 'OAS1', 'ZNF22', 'RHOC', 'CCL5'),
         ('HSPB1', 'CHD4', 'TRIAP1', 'CD3G', 'C19orf53', 'HES1', 'WIBG', 'PNN', 'S1PR5', 'HLA-DQB1'),
         ('IL2RG', 'SOD2', 'ERH', 'MAD1L1', 'NDUFB11', 'DNAJC7', 'HLA-DQB1', 'U2AF1', 'GCHFR', 'ELOVL5'),
         ('TPR', 'HHEX', 'CHCHD10', 'KLF6', 'NDUFB2', 'FCGR3A', 'SRM', 'EIF3D', 'DDX39A', 'GSTP1'),
         ('TOMM7', 'POLR2I', 'NAP1L1', 'CD40LG', 'UBE2J1', 'CST3', 'BLK', 'AIF1', 'SAMD3', 'BFAR'),
         ('MANF', 'SUB1', 'PSMC3', 'HLA-DRB1', 'PRDX6', 'NUCKS1', 'CD52', 'GATA2', 'NOP56', 'IRF8'),
         ('ESD', 'AC084018.1', 'GOPC', 'EBPL', 'NOP56', 'NUCB2', 'LSM4', 'IL18', 'GSTP1', 'ALOX5AP'),
         ('HMGB2', 'HSPB1', 'EIF4A1', 'IFT20', 'DUSP2', 'ERH', 'CD82', 'RPS24', 'IFITM1', 'GZMB'),
         ('ANKRD12', 'IDH3B', 'SAMD3', 'EIF3I', 'S1PR4', 'PILRA', 'FCRLA', 'TTC3', 'SF3B2', 'CD300A'),
         ('GNAI2', 'RNF34', 'SDHC', 'IL2RG', 'H2AFJ', 'GBP2', 'NDUFB11', 'GOPC', 'BLOC1S4', 'H2AFJ'),
         ('HMOX2', 'IRF7', 'EIF3I', 'DGCR6L', 'LAT', 'SNHG15', 'NDUFAF3', 'PAFAH1B3', 'HSP90AB1', 'CXCR4'),
         ('APH1A', 'ATP6V0E1', 'PNN', 'CD3E', 'OST4', 'GIMAP7', 'EBP', 'SRSF7', 'EIF3G', 'LSM4'),
         ('LY9', 'NDUFA8', 'PSMG2', 'LMAN2', 'HIGD2A', 'HMOX1', 'U2AF1L4', 'TSC22D1', 'CYB561A3', 'SPI1'),
         ('MAPKAPK5-AS1', 'ATP5I', 'C19orf53', 'EIF4H', 'CHCHD10', 'NDUFB10', 'PLP2', 'IDH2', 'CALM1', 'HLA-DRB5'),
         ('ZFAS1', 'KLRG1', 'UPP1', 'HNRNPF', 'LYL1', 'SSU72', 'EMC7', 'SRSF2', 'NOP10', 'P2RY13'),
         ('IL2RB', 'TLN1', 'NEDD8', 'RABAC1', 'BCAS4', 'ITGA4', 'RPS27L', 'CTSW', 'MAD2L2', 'SLC39A3'),
         ('LDHB', 'SELT', 'SFPQ', 'MEAF6', 'IMPDH2', 'ADRBK1', 'PDAP1', 'DEK', 'CHST12', 'DNAJC1')],
        dtype=[('CD4+/CD25 T Reg', 'O'), ('CD4+/CD45RA+/CD25- Naive T', 'O'), ('CD4+/CD45RO+ Memory', 'O'), ('CD8+ Cytotoxic T', 'O'), ('CD8+/CD45RA+ Naive Cytotoxic', 'O'), ('CD14+ Monocyte', 'O'), ('CD19+ B', 'O'), ('CD34+', 'O'), ('CD56+ NK', 'O'), ('Dendritic', 'O')]),
  'params': {'groupby': 'bulk_labels',
   'method': 'logreg',
   'reference': 'rest',
   'use_raw': array([ True])},
  'scores': array([(0.36708045, 0.21345432, 0.25056472, 0.47380558, 0.49400362, 0.42869335, 0.38209128, 0.16252884, 0.27312252, 0.5761109 ),
         (0.33053437, 0.20233947, 0.22161192, 0.45641452, 0.40868703, 0.33480608, 0.27576044, 0.14514004, 0.23263697, 0.41123936),
         (0.28874135, 0.18551603, 0.2174346 , 0.38137153, 0.3839347 , 0.31476367, 0.23305947, 0.14144188, 0.22539623, 0.37838832),
         (0.28116795, 0.1806243 , 0.21245584, 0.36773658, 0.34208363, 0.3001856 , 0.20124702, 0.13929126, 0.20584142, 0.35284704),
         (0.27577916, 0.17075457, 0.21028428, 0.36728293, 0.30850986, 0.29409873, 0.19335076, 0.12441165, 0.20464943, 0.34399125),
         (0.26630053, 0.16783811, 0.20674601, 0.32462662, 0.29299584, 0.28710747, 0.16601746, 0.12417085, 0.19732025, 0.326079  ),
         (0.24902259, 0.1548685 , 0.20456684, 0.27858233, 0.2680623 , 0.27944317, 0.16429739, 0.1236445 , 0.19572873, 0.31131235),
         (0.24685156, 0.15351592, 0.20234181, 0.27262518, 0.2673843 , 0.27893484, 0.15945351, 0.12100429, 0.18239562, 0.30909538),
         (0.24642229, 0.14786571, 0.19955169, 0.26972947, 0.25856474, 0.27285635, 0.15266137, 0.11485746, 0.18132254, 0.3017958 ),
         (0.23931383, 0.1418957 , 0.19718477, 0.26062533, 0.25515258, 0.27179334, 0.14877735, 0.11423945, 0.16874497, 0.29823115),
         (0.23610765, 0.13923335, 0.19589016, 0.25510928, 0.2481284 , 0.26503623, 0.14775637, 0.11152696, 0.15969871, 0.2943058 ),
         (0.23583865, 0.1391585 , 0.19130895, 0.25185868, 0.24017274, 0.25833008, 0.14755163, 0.09573594, 0.15398742, 0.29203504),
         (0.23543657, 0.13727468, 0.19082192, 0.24134913, 0.23766583, 0.25604963, 0.14156154, 0.09508502, 0.15299046, 0.2885744 ),
         (0.21073186, 0.13605753, 0.18859474, 0.24029425, 0.21798728, 0.25491044, 0.13172081, 0.09443832, 0.15070012, 0.2875855 ),
         (0.20635183, 0.13521907, 0.18466896, 0.24028558, 0.21684732, 0.25437054, 0.13085546, 0.09423181, 0.1430881 , 0.2831326 ),
         (0.20497234, 0.13273571, 0.18366021, 0.23301765, 0.21414515, 0.2502589 , 0.12993497, 0.09224461, 0.1351248 , 0.27849504),
         (0.20280421, 0.13141866, 0.18332833, 0.22603393, 0.2135516 , 0.24958467, 0.12691736, 0.08859195, 0.12080148, 0.276801  ),
         (0.20261179, 0.12984557, 0.18045065, 0.20878746, 0.2068858 , 0.24884686, 0.1240931 , 0.08851102, 0.11878243, 0.27245894),
         (0.19984183, 0.12637442, 0.17741713, 0.2025947 , 0.20469254, 0.23635809, 0.12365932, 0.08832898, 0.11787237, 0.27075803),
         (0.19763033, 0.1261706 , 0.17520925, 0.20094189, 0.20232713, 0.23545915, 0.12182632, 0.08672539, 0.11364051, 0.2515854 ),
         (0.19629215, 0.12598358, 0.17241125, 0.19758883, 0.19671473, 0.23426138, 0.12114646, 0.08609711, 0.11316794, 0.24943483),
         (0.19539504, 0.12359719, 0.16939946, 0.19430761, 0.1940633 , 0.23328668, 0.11924695, 0.08354113, 0.11177313, 0.24448204),
         (0.1932787 , 0.12343675, 0.16493334, 0.1932864 , 0.19265564, 0.23197092, 0.11924591, 0.08315832, 0.11111486, 0.23656891),
         (0.19302633, 0.12312193, 0.1607495 , 0.19281888, 0.19189632, 0.23108095, 0.11876089, 0.08292127, 0.11074634, 0.23414572),
         (0.19210656, 0.11446455, 0.15927903, 0.19209224, 0.19182624, 0.22344439, 0.1176447 , 0.08172187, 0.1102796 , 0.23167899),
         (0.18438897, 0.1133637 , 0.15580373, 0.18739998, 0.191318  , 0.22204468, 0.11750899, 0.08040652, 0.11025239, 0.22637872),
         (0.18387298, 0.1128    , 0.15452933, 0.18733002, 0.18963297, 0.2199674 , 0.11657318, 0.07903691, 0.10217047, 0.22558196),
         (0.18358126, 0.11020698, 0.15318537, 0.1858809 , 0.1890883 , 0.21904378, 0.11597035, 0.07902833, 0.10065546, 0.2234609 ),
         (0.1817688 , 0.10951684, 0.15308808, 0.18091898, 0.1875665 , 0.21664412, 0.115629  , 0.07828778, 0.09871125, 0.22328721),
         (0.18089342, 0.10918269, 0.15015858, 0.18062276, 0.1811695 , 0.21648452, 0.11410622, 0.07662476, 0.09850229, 0.21157356),
         (0.17967255, 0.10798191, 0.149418  , 0.17449039, 0.18035111, 0.21630505, 0.11181161, 0.07637715, 0.09819261, 0.21046771),
         (0.17367063, 0.10713113, 0.14941487, 0.17378807, 0.17994899, 0.20710309, 0.1109236 , 0.07514533, 0.0967216 , 0.20882319),
         (0.17357609, 0.10710248, 0.1493381 , 0.17352448, 0.17842305, 0.2066336 , 0.11078716, 0.07440689, 0.0950389 , 0.20690924),
         (0.1732831 , 0.10659743, 0.14799273, 0.1709472 , 0.17701308, 0.20540912, 0.11071802, 0.07382797, 0.09182671, 0.20532812),
         (0.17143407, 0.10365353, 0.1474269 , 0.16940722, 0.16924948, 0.19976693, 0.11045037, 0.0737152 , 0.09020674, 0.20468065),
         (0.17049022, 0.10208206, 0.14434391, 0.16896987, 0.16900352, 0.19849557, 0.10645165, 0.07301053, 0.0868604 , 0.2033435 ),
         (0.16993338, 0.1011026 , 0.144255  , 0.16641068, 0.16318208, 0.19563973, 0.10516747, 0.07100513, 0.08537536, 0.2000839 ),
         (0.16758175, 0.09956119, 0.14233199, 0.16619347, 0.16119826, 0.1913862 , 0.10278513, 0.07091787, 0.08446885, 0.19764577),
         (0.16557603, 0.09936191, 0.14027275, 0.16275163, 0.16048357, 0.18882042, 0.1016388 , 0.0694366 , 0.08351868, 0.1971625 ),
         (0.15764487, 0.09865338, 0.13933538, 0.1613434 , 0.15923926, 0.18779013, 0.10087138, 0.06789809, 0.08331722, 0.19598989),
         (0.1566999 , 0.09727442, 0.13768058, 0.16112496, 0.15901786, 0.18735431, 0.10035495, 0.06781339, 0.08313235, 0.19428238),
         (0.15523458, 0.09719263, 0.13568424, 0.15905894, 0.15617926, 0.1848341 , 0.10010639, 0.06551021, 0.08274136, 0.19032131),
         (0.15458843, 0.09704837, 0.13355313, 0.15779011, 0.15457907, 0.18318906, 0.0984956 , 0.06526961, 0.08182982, 0.18824615),
         (0.14959757, 0.09702687, 0.13320997, 0.15649897, 0.15345116, 0.18244354, 0.09816285, 0.06468542, 0.08144877, 0.18727575),
         (0.14780729, 0.09615972, 0.1328532 , 0.1561454 , 0.15290989, 0.18046197, 0.09747288, 0.06426445, 0.07989997, 0.18588789),
         (0.1473683 , 0.09552819, 0.1311807 , 0.15452516, 0.15169758, 0.17637062, 0.09637336, 0.06425755, 0.07647365, 0.18490782),
         (0.14626096, 0.09496253, 0.13048337, 0.1536426 , 0.15133104, 0.17626663, 0.0953012 , 0.06397749, 0.0756576 , 0.18435502),
         (0.14550824, 0.09097257, 0.1303379 , 0.1533697 , 0.14843738, 0.17621517, 0.09511708, 0.06328156, 0.07556168, 0.18398224),
         (0.14485206, 0.09083202, 0.13025315, 0.15319222, 0.14768708, 0.1756372 , 0.09505042, 0.06298079, 0.07518866, 0.18278366),
         (0.144628  , 0.09038807, 0.12958793, 0.151246  , 0.14708641, 0.17493117, 0.09372274, 0.06292623, 0.07491615, 0.18137942),
         (0.14307244, 0.08804047, 0.12901472, 0.15076847, 0.1399712 , 0.16440693, 0.09330817, 0.06232318, 0.07411947, 0.1810734 ),
         (0.14220001, 0.08595284, 0.12865701, 0.1500081 , 0.13965619, 0.16329521, 0.09323607, 0.06182744, 0.07387868, 0.17959888),
         (0.13998479, 0.08545638, 0.12786572, 0.14826432, 0.13818733, 0.15950158, 0.09150271, 0.06163419, 0.07317071, 0.17830047),
         (0.1394364 , 0.08527729, 0.12646408, 0.14794631, 0.13795604, 0.15718172, 0.09080991, 0.06094709, 0.07234892, 0.17586191),
         (0.13839109, 0.08478693, 0.12372864, 0.14644042, 0.13720246, 0.15709578, 0.08962585, 0.05896161, 0.070723  , 0.1738831 ),

In [27]:
adata.layers["log_transformed"] = np.log1p(adata.X)
adata

/tmp/ipykernel_7085/2818935080.py:1: RuntimeWarning: divide by zero encountered in log1p
  adata.layers["log_transformed"] = np.log1p(adata.X)
/tmp/ipykernel_7085/2818935080.py:1: RuntimeWarning: invalid value encountered in log1p
  adata.layers["log_transformed"] = np.log1p(adata.X)

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain', 'cell_type'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups', 'random'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs', 'gene_stuff'
    layers: 'log_transformed'
    obsp: 'connectivities', 'distances'

In [28]:
adata.to_df(layer="log_transformed")

index,HES4,TNFRSF4,SSU72,PARK7,RBP7,SRM,MAD2L2,AGTRAP,TNFRSF1B,EFHD2,...,ATP5O,MRPS6,TTC3,U2AF1,CSTB,SUMO3,ITGB2,S100B,PRMT2,MT-ND3
index,,,,,,,,,,,,,,,,,,,,,
AAAGCCTGGCTAAC-1,-0.394525,-0.211956,-1.301953,-0.358105,1.478418,-0.757153,1.103931,1.476364,1.764902,-0.744440,...,-0.157824,-0.759287,-0.417032,0.264669,0.877134,1.666574,0.418052,-0.235722,-1.010601,1.611636
AAATTCGATGCACA-1,0.775188,-0.211956,0.585005,NaN,-0.191161,-0.757153,1.060910,-0.665532,-0.614336,-0.744440,...,NaN,-0.759287,-0.417032,-2.353878,1.347813,-0.879477,0.775648,-0.235722,1.289233,-0.673345
AACACGTGGTCTTT-1,-0.394525,-0.211956,0.394067,NaN,-0.191161,-0.757153,-0.599657,0.678541,-0.614336,1.189671,...,NaN,1.282599,-0.417032,-2.353878,-0.606969,-0.879477,0.543486,-0.235722,0.508623,-0.673345
AAGTGCACGTGCTA-1,-0.394525,-0.211956,0.757998,-0.170788,-0.191161,-0.757153,-0.599657,-0.665532,-0.614336,-0.744440,...,0.770571,-0.759287,-0.417032,-2.353878,-0.126698,-0.879477,0.568717,-0.235722,-1.010601,-0.673345
ACACGAACGGAGTG-1,-0.394525,-0.211956,-1.301953,-0.933946,-0.191161,-0.757153,-0.599657,0.580538,-0.614336,1.075685,...,NaN,0.609222,0.985444,-0.114289,-0.763570,-0.879477,-0.007025,-0.235722,-1.010601,-0.673345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGGCACCTCCAACA-8,-0.394525,-0.211956,0.316270,-0.877070,-0.191161,0.411447,-0.599657,1.150572,-0.614336,0.560187,...,0.946238,-0.759287,1.014506,0.947014,0.053541,-0.879477,0.445327,-0.235722,0.433729,1.278988
TGTGAGTGCTTTAC-8,1.426956,-0.211956,-1.301953,NaN,-0.191161,-0.757153,-0.599657,-0.665532,-0.614336,0.930588,...,NaN,-0.759287,-0.417032,0.359072,0.561329,-0.879477,-0.187535,-0.235722,0.818898,-0.673345
TGTTACTGGCGATT-8,-0.394525,-0.211956,-1.301953,NaN,-0.191161,1.023889,-0.599657,-0.665532,-0.614336,-0.744440,...,-0.479650,-0.759287,-0.417032,1.050122,0.595534,-0.879477,0.141500,-0.235722,-1.010601,0.800206
TTCAGTACCGGGAA-8,-0.394525,-0.211956,-1.301953,-0.487760,-0.191161,-0.757153,-0.599657,-0.665532,-0.614336,-0.744440,...,NaN,-0.759287,-0.417032,1.217284,0.350657,0.635518,-0.394525,-0.235722,-1.010601,-0.673345
TTGAGGTGGAGAGC-8,-0.394525,-0.211956,0.138021,0.566450,-0.191161,0.260825,-0.599657,-0.665532,0.408793,-0.744440,...,NaN,-0.759287,-0.417032,0.728997,-0.988861,-0.879477,0.214305,-0.235722,-1.010601,-0.673345

In [29]:
adata.write('my_results.h5ad', compression="gzip")

In [32]:
!apt-get install hdf5-tools

adata.write('my_results.h5ad', compression="gzip")

!h5ls 'my_results.h5ad'

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  hdf5-tools
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 347 kB of archives.
After this operation, 1,255 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 hdf5-tools amd64 1.10.7+repack-4ubuntu2 [347 kB]
Fetched 347 kB in 1s (250 kB/s)
Selecting previously unselected package hdf5-tools.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../hdf5-tools_1.10.7+repack-4ubuntu2_amd64.deb ...
Unpacking hdf5-tools (1.10.7+repack-4ubuntu2) ...
Setting up hdf5-tools (1.10.7+repack-4ubuntu2) ...
Processing triggers for man-db (2.10.2-1) ...
X                        Dataset {700, 765}
layers                   Group
obs                      Group
obsm                     Group
obsp                     Group
raw                      Group
uns                      Group
var                      Group
varm                     Group
varp                     Group

In [33]:
obs_meta = pd.DataFrame({
        'time_yr': np.random.choice([0, 2, 4, 8], adata.n_obs),
        'subject_id': np.random.choice(['subject 1', 'subject 2', 'subject 4', 'subject 8'], adata.n_obs),
        'instrument_type': np.random.choice(['type a', 'type b'], adata.n_obs),
        'site': np.random.choice(['site x', 'site y'], adata.n_obs),
    },
    index=adata.obs.index,    # these are the same IDs of observations as above!
)

In [34]:
adata = ad.AnnData(adata.X, obs=obs_meta, var=adata.var)

In [35]:
print(adata)

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'

In [36]:
adata

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'

In [38]:
adata[:5, ['HES4', 'TNFRSF4']]

View of AnnData object with n_obs × n_vars = 5 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'

In [39]:
# Use actual gene names from your data
adata_subset = adata[:5, ['HES4', 'SSU72']].copy()

In [40]:
# Replace 'Gene_1' with an actual gene name like 'HES4'
print(adata[:3, 'HES4'].X.toarray().tolist())
adata[:3, 'HES4'].X = [0, 0, 0]
print(adata[:3, 'HES4'].X.toarray().tolist())

[[-0.32600000500679016], [1.1710000038146973], [-0.32600000500679016]]
[[0.0], [0.0], [0.0]]

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:630: FutureWarning: Setting element `.X` of view of `AnnData` object will obey copy-on-write semantics in the next minor release.
  if self._handle_view_X_cow(value):
/tmp/ipykernel_7085/916116967.py:3: ImplicitModificationWarning: Modifying `X` on a view results in data being overridden
  adata[:3, 'HES4'].X = [0, 0, 0]

In [41]:
# Use actual gene names (replace with real names from your data)
adata_subset = adata[:3, ['HES4', 'TNFRSF4']]

In [42]:
adata_subset

View of AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'

In [43]:
adata_subset.obs['foo'] = range(3)

/tmp/ipykernel_7085/2955902014.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata_subset.obs['foo'] = range(3)

In [44]:
adata_subset.obs['foo'] = range(3)

In [45]:
adata_subset

AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site', 'foo'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'

In [46]:
adata[adata.obs.time_yr.isin([2, 4])].obs.head()

                  time_yr subject_id instrument_type    site
index
AAATTCGATGCACA-1        4  subject 2          type a  site y
AAGTGCACGTGCTA-1        2  subject 2          type b  site x
ACAGTTCTTAGCCA-1        2  subject 8          type b  site y
ACCCTCGAGTGAGG-1        4  subject 8          type b  site x
ACTGGCCTTTTCGT-1        4  subject 8          type a  site x

In [48]:
import scanpy as sc
import anndata as ad

# Option 1: Using scanpy (recommended)
adata = sc.read('my_results.h5ad', backed='r')

# Option 2: Using anndata
adata = ad.read_h5ad('my_results.h5ad', backed='r')

In [49]:
adata.isbacked

True

In [50]:
adata.filename

PosixPath('my_results.h5ad')

In [51]:
adata.file.close()